title = "Custom Gitleaks Configuration for Sensitive Info"

# AWS Access Key Detection
[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["AWS", "key"]

# Generic API Key Detection
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api_key|apikey|secret|token|password)[\s:=]+['"][A-Za-z0-9_\-]{20,50}['"]'''
tags = ["API", "key"]

# JWT Token Detection
[[rules]]
id = "jwt-token"
description = "JWT Token"
regex = '''eyJ[a-zA-Z0-9_-]{32,}\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+'''
tags = ["JWT", "token"]

# NextAuth Secret Detection
[[rules]]
id = "nextauth-secret"
description = "NextAuth Secret Key"
regex = '''(?i)NEXTAUTH_SECRET\s*=\s*["'][A-Za-z0-9_\-]{32,}["']'''
tags = ["NextAuth", "secret"]

# MongoDB URI Detection
[[rules]]
id = "mongo-uri"
description = "MongoDB Connection String"
regex = '''mongodb(\+srv)?:\/\/[a-zA-Z0-9:_-]+:[a-zA-Z0-9%_-]+@([a-zA-Z0-9._-]+)\/[a-zA-Z0-9_-]+'''
tags = ["MongoDB", "database", "uri"]

# Stripe Secret Key Detection
[[rules]]
id = "stripe-secret-key"
description = "Stripe Secret Key"
regex = '''sk_live_[0-9a-zA-Z]{24}'''
tags = ["Stripe", "secret"]

# GitHub Token Detection
[[rules]]
id = "github-token"
description = "GitHub Personal Access Token"
regex = '''ghp_[0-9A-Za-z]{36}'''
tags = ["GitHub", "token"]
