name: Deploy to EC2

on:
  push:
    branches:
      - master # or main, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/LifePubUC/app/server
            
            # Pull latest code
            git pull origin master
            
            # Build and restart Docker containers
            docker-compose -f docker-compose.yml down
            docker-compose -f docker-compose.yml up -d --build
            
            # Clean up unused Docker images
            docker image prune -f
          EOF
