name: Secret Scan

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Gitleaks to scan for secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .github/gitleaks.toml # Custom rules for better accuracy
          report-format: "json"
          fail: true # Ensures it fails if secrets are found
          github-token: ${{ secrets.GH_TOKEN_2 }} # Uses GitHub's built-in token

      - name: Fail if secrets are found
        if: failure()
        run: echo "⚠️ Gitleaks detected sensitive information! Check logs." && exit 1
